replicaCount: 3

image:
  repository: yatharth31/flask-demo-app
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  host: flask-app.example.com
  path: /
