replicaCount: 1

image:
  repository: yatharth31/flask-demo-app
  tag: latest

service:
  type: NodePort
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  host: flask-app.local
  path: /

database:
  enabled: true
  image: postgres:15
  name: flaskdb
  user: flaskuser
  password: flaskpass
  storage: 1Gi
